# in this notebook, we're going to cover some of the most fundemental concepts of tensors using tensorflow

More specifically, we're going to cover:
    introduction to tensors
    getting information from tensors
    Manipulating tensors
    Tensors & Numpy
    Using @tf.function (a way to speed up your regular python functions)
    Using GPUs with tensorflow (or TPUs)
    Exercises to try for yourself!

### Introduction to Tensors


In [4]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [5]:
import sys
print(sys.executable)
!{sys.executable} -m pip show tensorflow


C:\Users\Eren\anaconda3\envs\tf_env\python.exe
Name: tensorflow
Version: 2.16.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\eren\anaconda3\envs\tf_env\lib\site-packages
Requires: tensorflow-intel
Required-by: 


# Create tensors with tf.constant()

In [7]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
## Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
# Create a vector
vector = tf.constant ([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [10]:
# Check the dimension of our vector
vector.ndim

1

In [11]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant ([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
matrix.ndim

2

In [13]:
# Create another matrix
another_matrix = tf.constant ([[10.,7.],
                               [3.,2.],
                               [8.,9.]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
# what's the number dimensions of another_matrix?
another_matrix.ndim

2

In [15]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [16]:
tensor.ndim

3

What We've created so far;

* scalar: a single number (without a direction)
* vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar,
  a 1-dimensional tensor is a vector)

### Creating Tensors with tf.Variable

In [19]:
# Create the same tensor with tf.Variable() as above
tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [20]:
# Let's try to change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [21]:
# Let's try to change one of the elements in our unchangeable tensor
#unchangeable_tensor[0].assign(7)

# Creating Random Tensors with TensorFlow

In [23]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2  = random_2.normal(shape=(3,2))

# Are they equal? 
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in a  tensor

In [25]:
 # Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [26]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [27]:
# Shuffle our non-shuffled tensor
#tf.random.set_seed(42)
#tf.random.shuffle(not_shuffled,seed=42)

In [28]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.57519627], shape=(1,), dtype=float32)
tf.Tensor([0.7266469], shape=(1,), dtype=float32)


In [29]:
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.4362378], shape=(1,), dtype=float32)
tf.Tensor([0.4056213], shape=(1,), dtype=float32)


In [30]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [31]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [32]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed =42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

It looks like if we want our shuffled tensors to be in the same order, we've 
got to use the global level random seed as well as the operation level random seed:
Rule:
If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

## Other ways to make tensors

In [35]:
import numpy as np
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None, layout=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or a 1-D `Tensor` of
        type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
      layout: Optional, `tf.experimental.dtensor.Layout`. If provided, the result
        is a [DTensor](https://www.tensorflow.org/guide/dtensor_overview) with the
        provided layout.
    
  

In [36]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [37]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors
 The Main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU (Much faster for numerical computing). 

In [39]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [40]:
numpy_A = np.arange(1,25, dtype = np.int32) # create a Numpy array between 1 to 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [41]:
A = tf.constant(numpy_A,shape =(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [42]:
C = tf.constant(numpy_A,shape =(3,8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [43]:
A.ndim

3

# Getting Information from your Tensors
When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [45]:
# Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [47]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [48]:
# Get various attributes of our tensor
print("Data type of every element",rank_4_tensor.dtype)
print("Number of dimensions (rank): ",rank_4_tensor.ndim)
print("Shape of tensor",rank_4_tensor.shape)
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])
print("Elements along the last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor).numpy())

Data type of every element <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing Tensors
Tensors can be indexed just like python lists


In [50]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [51]:
tenso1 = tf.random.Generator.from_seed(42)
tenso1 = tenso1.normal(shape=(2,3,4,5))

tenso1


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ,
          -0.23193763],
         [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 ,
          -0.57166284],
         [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263,
          -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,
           0.99009085]],

        [[-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ,
          -0.48293006],
         [-0.52447474, -1.0345329 ,  1.3066901 , -1.5184573 ,
          -0.4585211 ],
         [ 0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 ,
          -1.2659091 ],
         [-0.47450137,  2.006022  ,  0.28288034, -0.30288252,
          -1.443651  ]],

        [[ 1.0034493 ,  0.20857747,  0.35700995,  1.0648885 ,
           1.2432485 ],
         [-2.2173238 ,  0.18706243,  0.6617961 ,  0.01380118,
          -0.24827152],
         [ 1.2111493 , -0.7199124 , -0.04082382,  2.6791053 ,
           1.0914806

In [52]:
tenso1[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702],
         [-1.8107855 ,  0.09988727]],

        [[-0.0876323 , -0.635568  ],
         [-0.52447474, -1.0345329 ]]],


       [[[ 0.49689844,  0.8259971 ],
         [-0.92161775,  0.268676  ]],

        [[-2.5255601 ,  0.05080947],
         [ 1.3212339 ,  0.34584793]]]], dtype=float32)>

In [53]:
tenso2 = tf.constant([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
tenso2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [54]:
tenso2[:][:1][:1]

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])>

In [55]:
Y  = np.arange(0,120)
tenso3 =tf.constant(Y,shape=[2,3,4,5])
tenso3

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])>

In [56]:
tenso3[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 5,  6]],

        [[20, 21],
         [25, 26]]],


       [[[60, 61],
         [65, 66]],

        [[80, 81],
         [85, 86]]]])>

In [57]:
# Get the first element from each dimension from each index except for the final one
tenso3[:1,:1,:, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[ 0],
         [ 5],
         [10],
         [15]]]])>

### Expanding or Reshaping tensors


In [59]:
# Create a rank 2 tensor (2 dimensions)
np_4_rank2_tensor = np.arange(16)
rank_2_tensor = tf.constant(np_4_rank2_tensor,shape = [4,4])
rank_2_tensor.ndim, rank_2_tensor.shape
rank_2_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])>

In [60]:
 # Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  7, 11, 15])>

In [61]:
rank_2_tensor[:,-1].numpy()

array([ 3,  7, 11, 15])

### ADD in Extra dimension to tensor

In [63]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(4, 4, 1), dtype=int32, numpy=
array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]]])>

In [64]:
rank_3_tensor.ndim

3

In [65]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(4, 4, 1), dtype=int32, numpy=
array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]]])>

In [66]:
tf.expand_dims(rank_2_tensor,axis=0) # "0" means expand from the first axis

<tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])>

# Manipulating Tensors (Tensor operations)
**Basic operations** 
* "+", "-", "*", "/"

In [68]:
# You can add values to a tensor using the addition operator
tensor5  = tf.constant ([[10,7],[3,4]])
tensor5 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [69]:
tensor5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [70]:
# Original tensor is unchanged
tensor5 = tensor5 +10
tensor
# yapılırsa ancak değişiyor. Bu constant kullanımı

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [71]:
tensor6 = tf.Variable([[10,7],[3,4]])
tensor6

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [72]:
tensor6 +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [73]:
tensor6

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

#### Demek ki neymiş constant olması ile alakalı değilmiş burada yapılan normal işlemler kalıcı olarak etkilemiyor sonucu


In [75]:
 tensor5 *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [76]:
tensor5 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [77]:
# We can use the ensorflow built-in functions
tf.multiply(tensor5,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [78]:
tf.multiply(tensor6,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [79]:
tensor6

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [80]:
tf.multiply(tensor5,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [81]:
tensor5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [82]:
tf.math.add(tensor5,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]])>

In [83]:
tensor5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [84]:
tensor6

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

 # MATRİX MULTIPLICATION
 In machine learning, matrix multiplication is one of the most common tensor operations.


In [86]:
# Matrix multiplication

tf.linalg.matmul(tensor5,tensor6)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[251, 208],
       [172, 147]])>

In [87]:
# Matrix multiplication with Python operator "@"
tensor5 @ tensor6

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[251, 208],
       [172, 147]])>

In [88]:
tensor5.shape
tensor6.shape

TensorShape([2, 2])

In [89]:
# Create a tensor (3,2)
X1 = np.arange(1,7)
X1
tensor7 =tf.constant(X1,shape=[2,3])
# Create another (3,2) tensor
Y1 = np.arange(7,13)
tensor8 = tf.constant(Y1,shape=[3,2])

In [90]:
tensor7, tensor8

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [91]:
tf.linalg.matmul(tensor7,tensor8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

**! The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix!**
* İlk matrix'in sütun sayısı ile 2. matrix'in satır sayısının eşit olması lazım matrix multiplication yapılabilmesi için

### There are two rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:
1. the inner dimensions must match
2. the resulting matrix has the shape of the inner dimensions

In [94]:
# İncompatiable olan tensorlerin şeklini değiştirebilmek için ayrıca tf.reshape()'de kullanılabilir;
tf.reshape(tensor7,shape=(3,2))
tensor7, tensor8

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [95]:
# Try to matrix multiply X by reshape Y 
tensor8 @ tf.reshape(Y1,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[129, 144, 159],
       [163, 182, 201],
       [197, 220, 243]])>

In [96]:
tensor7,tf.transpose(tensor7)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]])>)

In [97]:
tensor7,tensor8


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [98]:
tf.reshape(tensor7,shape=(3,2))
tensor7
tf.matmul(tensor7,tensor8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

#### **The Dot Product** 
Matrix multiplication is also referred to as the dot product.
You can perform matrix multiplication using:
* tf.linalg.matmul()
* tf.tensordot()
  

In [100]:
# Perform the dot product on tensor7 and tensor8 (requires X or Y to be transposed)
tf.tensordot(tensor7,tensor8,axes= 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [101]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [102]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [103]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [104]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [105]:
#Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [106]:
# Perform the doc product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [107]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [108]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape =(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [109]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:",Y)
print("Y reshaped to (2,3)",tf.reshape(Y,shape=(2,3)))
print("Y transposed",tf.transpose(Y))

Normal Y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Y reshaped to (2,3) tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y transposed tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


**Generally,when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tensors to satisfy matrix multiplication rules.**

### Changing the datatype of a Tensor

In [112]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [113]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [114]:
D = tf.cast(B,dtype = tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [115]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [116]:
E_float16 = tf.cast(E,dtype=tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

# Aggregating Tensors
Aggregating tesors = Condensing them from multiple values down from a smaller amount of values

In [118]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [119]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [121]:
# Creating a random tensor  with values between 0-100 of size 50
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([18, 53, 49, 41,  1, 32, 20, 70, 69, 59, 34, 75,  6, 16, 31,  0, 38,
       91, 87, 98, 54, 89, 80, 65, 33, 52, 18, 86,  0, 44, 54,  5, 26, 69,
       28, 67, 67, 39, 86,  2, 41, 19, 96, 25, 83, 38, 66, 20, 41,  2])>

In [122]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [123]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [124]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [125]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [126]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2283>

In [127]:
# Find the variance and standart deviation
F = tf.cast(E,dtype=tf.float32)
tf.math.reduce_variance(F)

<tf.Tensor: shape=(), dtype=float32, numpy=822.02435>

In [128]:
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float32, numpy=28.670967>

# **Find the positional maximum and minimum**

In [130]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G, G.dtype

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 tf.float32)

In [131]:
# Find the positional maximum
tf.argmax(G)
#help(tf.argmax)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [132]:
np.argmax(G)

42

In [133]:
# Index on our largest value position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [134]:
# Find the max value of G
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [135]:
# Check for equality
G[tf.argmax(G)] ==tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [136]:
# Find the positional minimum
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [137]:
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (Removing all the single dimensions)

In [139]:
# Create a tensor to get started
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [140]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [141]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### ONE HOT ENCODING  TENSORS

In [143]:
# Create a list of indices
some_list = [0,1,2,3] # could be red,green blue, purple

#One hot encode our list of indices
tf.one_hot(some_list,depth=(4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [144]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="+",off_value="-")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'+', b'-', b'-', b'-'],
       [b'-', b'+', b'-', b'-'],
       [b'-', b'-', b'+', b'-'],
       [b'-', b'-', b'-', b'+']], dtype=object)>

In [145]:
tf.one_hot(some_list,depth=(3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

### Squaring, log, square root

In [147]:
# Create a new tensor
I = tf.range(1,10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [148]:
# Square it
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [149]:
# Find the squareroot 
#It is not compatiable with int32 you need to change the dtype with tf.cast
J=tf.cast(I,dtype=tf.float32)
tf.sqrt(J)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [150]:
# Find the log
K = tf.cast(I,dtype= tf.float32)
tf.math.log(K)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy
TensorFlow interacts beautifully with with Numpy arrays.

In [152]:
# Create a tensor directly from a Numpy array
L = tf.constant(np.array([3.,7.,10.]))
L

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [153]:
# Convert our tensor back to a NumPy array
np.array(L), type(np.array(L))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [154]:
L.numpy(), type(L.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [155]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPUs

In [157]:
tf.config.list_physical_devices("GPU")


[]

In [207]:
avector = tf.constant(np.random.randint(0,16),shape =[2,2,4])
tf.reshape(avector,shape=[4,2,2])
avector


<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15]]])>

In [217]:
Ç=tf.expand_dims(avector,0)
avector,Ç

(<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
 array([[[15, 15, 15, 15],
         [15, 15, 15, 15]],
 
        [[15, 15, 15, 15],
         [15, 15, 15, 15]]])>,
 <tf.Tensor: shape=(1, 2, 2, 4), dtype=int32, numpy=
 array([[[[15, 15, 15, 15],
          [15, 15, 15, 15]],
 
         [[15, 15, 15, 15],
          [15, 15, 15, 15]]]])>)

In [223]:
#help(tf.constant)
tf.cast(avector,dtype=tf.float16)
tf.random.set_seed(42)
avector.ndim

3

In [229]:
avector
rank_4=avector[...,tf.newaxis]
rank_4

<tf.Tensor: shape=(2, 2, 4, 1), dtype=int32, numpy=
array([[[[15],
         [15],
         [15],
         [15]],

        [[15],
         [15],
         [15],
         [15]]],


       [[[15],
         [15],
         [15],
         [15]],

        [[15],
         [15],
         [15],
         [15]]]])>

In [240]:
tf.squeeze(rank_4)

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15]]])>

In [244]:
tf.transpose(rank_4)
tf.reshape(rank_4,shape=[4,4])

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])>

In [246]:
tf.math.add(rank_4,10)

<tf.Tensor: shape=(2, 2, 4, 1), dtype=int32, numpy=
array([[[[25],
         [25],
         [25],
         [25]],

        [[25],
         [25],
         [25],
         [25]]],


       [[[25],
         [25],
         [25],
         [25]],

        [[25],
         [25],
         [25],
         [25]]]])>

In [268]:
avector2 = tf.constant(np.random.randint(0,100,size = 16))
avector2

<tf.Tensor: shape=(16,), dtype=int32, numpy=array([99, 54, 45, 81, 32, 22, 62, 63, 34, 92, 29, 80, 82, 95, 32, 81])>

In [274]:
tf.tensordot(avector,tf.reshape(avector2,shape=[4,2,2]),1)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[3705, 3945],
         [2520, 4575]],

        [[3705, 3945],
         [2520, 4575]]],


       [[[3705, 3945],
         [2520, 4575]],

        [[3705, 3945],
         [2520, 4575]]]])>

In [264]:
help(tf.tensordot)

Help on function tensordot in module tensorflow.python.ops.math_ops:

tensordot(a, b, axes, name=None)
    Tensor contraction of a and b along specified axes and outer product.
    
    Tensordot (also known as tensor contraction) sums the product of elements
    from `a` and `b` over the indices specified by `axes`.
    
    This operation corresponds to `numpy.tensordot(a, b, axes)`.
    
    Example 1: When `a` and `b` are matrices (order 2), the case `axes=1`
    is equivalent to matrix multiplication.
    
    Example 2: When `a` and `b` are matrices (order 2), the case
    `axes = [[1], [0]]` is equivalent to matrix multiplication.
    
    Example 3: When `a` and `b` are matrices (order 2), the case `axes=0` gives
    the outer product, a tensor of order 4.
    
    Example 4: Suppose that \\(a_{ijk}\\) and \\(b_{lmn}\\) represent two
    tensors of order 3. Then, `contract(a, b, [[0], [2]])` is the order 4 tensor
    \\(c_{jklm}\\) whose entry
    corresponding to the indices \

In [278]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

In [326]:
#tf.tensordot(a, b, axes=1)
#a@tf.transpose(b)

In [298]:
tf.size(avector)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [296]:
tf.shape(avector)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 4])>

In [308]:
avector3 = tf.constant(np.random.normal(0,1,1500),shape=[5,300])
avector3

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[ 0.05700654, -2.20508406,  0.00751102, ...,  0.9636407 ,
         0.09437076, -0.73665308],
       [-0.35893176, -1.04710264, -1.43864711, ...,  0.5440283 ,
         0.08656985, -0.2298596 ],
       [-1.56361779, -1.4087271 , -2.02949606, ...,  0.80699621,
         0.77660766, -0.4011267 ],
       [-0.81034026,  1.84736086, -1.56672561, ..., -1.13822154,
        -1.75927128, -1.00676269],
       [-0.147786  ,  1.03086898,  0.28715875, ..., -1.3925779 ,
        -0.1377638 ,  0.25346578]])>

In [322]:
avector = tf.constant(np.random.randint(0,16,size=16),shape =[2,2,4])
avector2 = tf.constant(np.random.randint(0,100,size = 16))
avector,avector2


(<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
 array([[[ 2,  3, 13, 15],
         [ 1,  2,  6, 12]],
 
        [[ 2,  5, 12,  1],
         [14, 12,  1, 11]]])>,
 <tf.Tensor: shape=(16,), dtype=int32, numpy=array([23, 10, 61, 35, 70, 54, 30, 41, 66, 80, 23,  4,  7, 99, 75, 23])>)

In [324]:
tf.linalg.matmul(avector,tf.transpose(tf.reshape(avector2,shape=[2,4,2])))


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1589, 1417],
        [ 925, 1054]],

       [[ 884, 1391],
        [1065, 1520]]])>

In [328]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
atensor1 = tf.constant(np.random.normal(0,1,size =150528),shape = [224,224,3])

In [340]:
atensor1

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[ 0.60632551,  0.60428792, -0.7114919 ],
        [-0.46112912,  1.08710356, -0.41635932],
        [-0.06301745,  0.41615914, -1.12786451],
        ...,
        [ 1.53979285,  0.49978924, -0.23730386],
        [-1.87908223, -0.56437298, -0.02469936],
        [-0.65806254,  1.78850307, -0.03243216]],

       [[-0.09874995, -1.70638557, -1.1258768 ],
        [-0.44183258,  0.01276213, -0.27635973],
        [ 1.30590447,  1.25479578,  0.21244271],
        ...,
        [-2.24738291,  1.03771183, -0.63294209],
        [ 1.32420386,  0.35747341,  0.31046458],
        [-0.19510854, -0.20288484,  0.10104005]],

       [[-0.17862801,  0.17769102, -0.98852583],
        [ 0.14043597, -0.77991575, -0.06494794],
        [-0.27840213,  1.21891388, -0.68902723],
        ...,
        [-0.68605214, -0.1816908 ,  0.32995302],
        [-0.17563786, -0.84233678, -0.73861643],
        [-0.50045414, -0.50308688,  0.20240106]],

       ...,

     

In [367]:
tf.argmin(atensor1,axis=0)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[169,  35,  85],
       [185,  72, 105],
       [120, 141,  52],
       [  1, 200, 103],
       [120,  81,  59],
       [128,   2, 175],
       [ 72,  34, 215],
       [ 65, 206,   6],
       [ 12,  79, 118],
       [221, 111, 189],
       [ 58, 138, 113],
       [156, 163,   7],
       [217, 123, 100],
       [185,  11, 107],
       [103,  59, 112],
       [  4,  39, 132],
       [201, 188, 158],
       [213, 141, 176],
       [115,  31, 126],
       [209, 212, 222],
       [219,  10, 124],
       [195,  96,  55],
       [196, 151, 177],
       [ 12, 181,  55],
       [ 16, 192,   0],
       [178, 212, 145],
       [ 90,  76, 132],
       [ 57,  36, 111],
       [  1, 122, 111],
       [ 47, 189,  48],
       [  7, 199,   0],
       [113,  29, 138],
       [ 13,  62, 207],
       [164,  24, 157],
       [188, 162,  32],
       [ 97, 147,  59],
       [ 48, 119, 115],
       [111, 139,  24],
       [ 44,  81, 131],
       [ 28, 204

In [359]:
tf.shape(atensor1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([224, 224,   3])>

In [344]:
help(tf.argmin)

Help on function argmin_v2 in module tensorflow.python.ops.math_ops:

argmin_v2(input, axis=None, output_type=tf.int64, name=None)
    Returns the index with the smallest value across axes of a tensor.
    
    Returns the smallest index in case of ties.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float32`, `float64`,
        `int32`, `uint8`, `int16`, `int8`, `complex64`, `int64`, `qint8`,
        `quint8`, `qint32`, `bfloat16`, `uint16`, `complex128`, `half`, `uint32`,
        `uint64`.
      axis: A `Tensor`. Must be one of the following types: `int32`, `int64`.
        int32 or int64, must be in the range `-rank(input), rank(input))`.
        Describes which axis of the input Tensor to reduce across. For vectors,
        use axis = 0.
      output_type: An optional `tf.DType` from: `tf.int32, tf.int64`. Defaults to
        `tf.int64`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` of type `output_type`.
    
    

In [336]:
tf.reduce_min(atensor1)

<tf.Tensor: shape=(), dtype=float64, numpy=-4.443176822815754>

In [338]:
tf.reduce_max(atensor1)

<tf.Tensor: shape=(), dtype=float64, numpy=4.296856781832613>

In [369]:
tf.argmax(atensor1,axis=0)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[163, 198, 208],
       [175, 200,  46],
       [102,  93, 157],
       [ 96,  33, 146],
       [139, 155, 107],
       [155, 209, 181],
       [198, 174, 167],
       [112,  99, 111],
       [ 20,  40,  93],
       [ 97, 200, 207],
       [  4, 119,  43],
       [ 88,  69, 184],
       [127,  46, 105],
       [ 54, 210, 142],
       [203,  92,  29],
       [169, 120, 101],
       [200,  77, 198],
       [165, 212,  46],
       [ 54, 178, 221],
       [110,  65, 185],
       [209, 218,   3],
       [169,  91, 138],
       [ 39,  79, 103],
       [128, 159, 111],
       [ 20,  70, 216],
       [106, 117,  38],
       [ 57, 218, 148],
       [111,  41,  71],
       [186, 111,  70],
       [119, 190, 145],
       [141,  26, 118],
       [208, 189, 152],
       [147,  17,  96],
       [119,  95,  36],
       [ 51,  97, 185],
       [129, 145, 100],
       [ 83,  13, 162],
       [129, 206, 138],
       [ 28, 200, 149],
       [ 46,  62

In [371]:
atensor2 = tf.constant(np.random.normal(0,1,size =150528),shape = [1,224,224,3])

In [373]:
tf.shape(atensor2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  1, 224, 224,   3])>

In [377]:
atensor3 = tf.squeeze(atensor2)
tf.shape(atensor3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([224, 224,   3])>

In [393]:
some_list2 = [1,2,3,4,5,6,7,8]
tf.one_hot(some_list2,depth=(8))

<tf.Tensor: shape=(8, 8), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>